--VERI TABANINDAKÝ ÝKÝ TABLODAN VERI OKUYUP TEXTE YAZDIRMA

DECLARE
CURSOR DEPT_OKU IS SELECT DEPTNO,DNAME FROM DEPT;
REC_DEPT DEPT_OKU%ROWTYPE;


CURSOR EMP_OKU(P_DEPTNO DEPT.DEPTNO%TYPE) IS SELECT EMPNO, ENAME, SAL, JOB FROM EMP 
WHERE DEPTNO = P_DEPTNO ORDER BY EMPNO;


REC_EMP EMP_OKU%ROWTYPE;
PARAGRAF VARCHAR2(2000); -- CURSORDAN GELEN DEÐERLERÝ BURDA TOPLUCAZ
TXTDOSYA UTL_FILE.FILE_TYPE;
BEGIN
    TXTDOSYA:=UTL_FILE.FOPEN('TEXT_DIR','TXTDEMP1.TXT','W');
    OPEN DEPT_OKU;
    LOOP
        FETCH DEPT_OKU INTO REC_DEPT;
        EXIT WHEN DEPT_OKU%NOTFOUND;
        UTL_FILE.PUT_LINE(TXTDOSYA,'BÖLÜM NO VE ADI'||REC_DEPT.DEPTNO||' '||REC_DEPT.DNAME);
            OPEN EMP_OKU(REC_DEPT.DEPTNO);
            LOOP
                FETCH EMP_OKU INTO REC_EMP;
                EXIT WHEN EMP_OKU%NOTFOUND;
                PARAGRAF:= REC_EMP.EMPNO||' '||REC_EMP.ENAME||' '||REC_EMP.SAL||' '||REC_EMP.JOB;
                UTL_FILE.PUT_LINE(TXTDOSYA,PARAGRAF);
            END LOOP;
        CLOSE EMP_OKU;
    END LOOP;
    CLOSE DEPT_OKU;
    IF UTL_FILE.IS_OPEN(TXTDOSYA) THEN
        UTL_FILE.FCLOSE(TXTDOSYA);
    END IF;
END;
