-- PROCEDURES

-- ÖRNEK 2(IN OUT PARAMETRELÝ)
--SENARYO : BÖLÜM NUMARASINI GÖNDERÝP BÖLÜM ADINI ELDE EDECEÐÝMÝZ PROCEDURE

create OR REPLACE procedure 
  GET_DNAME (P_DEPTNO IN DEPT.DEPTNO%TYPE, P_DNAME OUT DEPT.DNAME%TYPE)IS
  BEGIN
    SELECT DNAME INTO P_DNAME FROM DEPT  WHERE DEPTNO=P_DEPTNO;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      P_DNAME := NULL;
  END ;
  /
DECLARE
--EMP TABLOSUNDA TÜM DEÐERLERÝ PARAMETRÝK OLARAK ALACAK BÝ PROSEDÜR ÝÇÝN CURSOR CREATE EDECEZ
  CURSOR C_EMP IS SELECT EMPNO,ENAME,DEPTNO FROM EMP;
  R_EMP C_EMP%ROWTYPE;
  WDNAME DEPT.DNAME%TYPE;
BEGIN
 OPEN C_EMP;
 LOOP
  FETCH C_EMP INTO R_EMP;
  EXIT WHEN C_EMP%NOTFOUND;
  GET_DNAME(R_EMP.DEPTNO, WDNAME); --CURSORDAN DÖNEN DEPTNOLARI WDNAME E ATADIK
  DBMS_OUTPUT.PUT_LINE('ÇALIÞAN NO-BÖLÜM NO- BÖLÜM ADI'||R_EMP.EMPNO||' '||R_EMP.ENAME||' '||WDNAME);
 
 END LOOP;
 CLOSE C_EMP;
END;
