--EXCEL DIRECTORY CREATE ETMEK
--PROCEDURE YAZIULCAK

CREATE OR REPLACE PROCEDURE CSV_EMP (P_SEP VARCHAR2) IS

    CURSOR OKU IS (SELECT E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
        FROM EMP E, DEPT D
        WHERE E.DEPTNO = D.DEPTNO);
        
    R_OKU OKU%ROWTYPE;
    WSATIR VARCHAR2(4000); -- CURSORDAN DÖNEN DEÐERLERÝ BURDA BÝRÝKTÝRCEZ
    DOSYA1 UTL_FILE.FILE_TYPE;
    HATALI_SEP EXCEPTION;
    
BEGIN
    IF P_SEP NOT IN (';','/') THEN
        RAISE HATALI_SEP;
    END IF;
        
    DOSYA1 := UTL_FILE.FOPEN(LOCATION => 'EXCEL_DIR', FILENAME => 'EMP_DEPT_CS.TXT', OPEN_MODE=>'W', MAX_LINESIZE =>32767);
    OPEN OKU;
    LOOP
        FETCH OKU INTO R_OKU;
        EXIT WHEN OKU%NOTFOUND;
        WSATIR := R_OKU.EMPNO|| P_SEP||R_OKU.ENAME||P_SEP||R_OKU.SAL||P_SEP;
        WSATIR :=WSATIR||R_OKU.DEPTNO||P_SEP||R_OKU.DNAME;
        
        UTL_FILE.PUT_LINE(DOSYA1,WSATIR);
        
    
    END LOOP;
    CLOSE OKU;
    UTL_FILE.FCLOSE(DOSYA1);
    EXCEPTION WHEN HATALI_SEP THEN
        DBMS_OUTPUT.PUT_LINE('>> SEPERATOR HATALI. ; VEYA / OLABÝLÝR');
        WHEN OTHERS THEN
        UTL_FILE.FCLOSE(DOSYA1);
        RAISE;            
END;