--FOR LOOP
--10DAN 20YE KADAR SAYI YAZDIRMA

DECLARE

BEGIN 
  FOR A IN (SELECT EMPNO,ENAME,SAL FROM EMP) LOOP
    DBMS_OUTPUT.PUT_LINE('EMPNO = '||A.EMPNO||'ENAME ='||A.ENAME||'SALARY ='||A.SAL);
  END LOOP;
END;