SET SERVEROUTPUT ON;
EXECUTE CALISANLAR.ZAM_YAP(0.1);

SELECT * FROM EMP;

SELECT ENAME, DEPTNO, CALISANLAR.BOLUM_ADI(DEPTNO) FROM EMP;

DECLARE 
  CURSOR OKU IS SELECT ENAME, SAL, DEPTNO, CALISANLAR.BOLUM_ADI(DEPTNO) BOLUM_ADI
  FROM EMP;
  R_OKU OKU%ROWTYPE;
BEGIN
  OPEN OKU;
  LOOP
  FETCH OKU INTO R_OKU;
  EXIT WHEN OKU%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE(R_OKU.ENAME||' '||R_OKU.SAL||' '||R_OKU.DEPTNO||'-'||R_OKU.BOLUM_ADI);
  END LOOP;
  CLOSE OKU;
END;