-- PROCEDURES

-- ÖRNEK 2(IN OUT PARAMETRELÝ)
--SENARYO : BÖLÜM NUMARASINI GÖNDERÝP BÖLÜM ADINI ELDE EDECEÐÝMÝZ PROCEDURE

create OR REPLACE procedure 
  GET_DNAME (P_DEPTNO IN DEPT.DEPTNO%TYPE, P_DNAME OUT DEPT.DNAME%TYPE)IS
  BEGIN
    SELECT DNAME INTO P_DNAME FROM DEPT  WHERE DEPTNO=P_DEPTNO;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      P_DNAME := NULL;
  END ;
  /
DECLARE
  WDNAME DEPT.DNAME%TYPE;
BEGIN
  GET_DNAME(10,WDNAME);
  DBMS_OUTPUT.PUT_LINE('ADI :'||WDNAME);
END;
