-- PROCEDURES

-- ÖRNEK 1 PARAMETRESÝZ PROCEDURE
SET SERVEROUTPUT ON
CREATE OR REPLACE 
PROCEDURE ILK_PROC 
IS 
BEGIN
DBMS_OUTPUT.PUT_LINE('BEN STORERD STAND ALONE BIR PROCEDURURUM');
END;

EXECUTE ILK_PROC;
