-- procedure parametre göndermek

CREATE OR REPLACE PROCEDURE SILINDIR_HACMI(R IN NUMBER, H IN NUMBER, P_SONUC OUT NUMBER) IS
  WSONUC NUMBER ;
  PI CONSTANT NUMBER :=3.1415;
BEGIN
  WSONUC := PI*R*R*H;
  P_SONUC := WSONUC;
  --DBMS_OUTPUT.PUT_LINE
END;
------------------
/
DECLARE
  GELEN_SONUC NUMBER;
BEGIN
  SILINDIR_HACMI(4,6,GELEN_SONUC);
  DBMS_OUTPUT.PUT_LINE('YARIÇAPI 4 YUKSEKLIÐI 6 OLAN SILINDIRIN HACMI =' ||GELEN_SONUC);
END;