--PL/SQL VERÝ TABANI PROGRAMLAMA-ADVANCED LEVEL UYGULAMALAR
--A - TEXT DOSYALARLA ÇALIÞMAK
--1)TABLO CREATE EDILMESÝ
--2)TEXT DOSYADAN VERI OKUMAK
--3)TEXT DOSYAYA VERI YAZMAK
	--A)BIR TEXT DOSYADAN VERI OKUYUP BASKA BIR DOSYAYA YAZACAGIZ
	--B)VERITABANINDAKI BIR TABLODAN VERI OKUYUP TEXT DOSYAYA YAZACAGIZ
	--C)VERITABANINDAKI IKI TABLODAN VERI OKUYUP TEXT DOSYAAY YAZACAGIZ
SET SERVEROUTPUT ON
DECLARE
TXT_DOSYA1 UTL_FILE.FILE_TYPE;
PARAGRAF VARCHAR2(2000); -- GETLINEDAN OKUYACAÐIMIZ DEÐERÝ BU DEÐÝÞKENE ATAYACAÐIZ
BEGIN
    TXT_DOSYA1:=UTL_FILE.FOPEN('TEXT_DIR','DOSYA.txt','R');-- BU BÝR FONKSÝYONDUR VE GERÝ DÖNÜÞ DEÐERÝ VARDIR
    LOOP
        BEGIN
        UTL_FILE.GET_LINE(TXT_DOSYA1,PARAGRAF);
        DBMS_OUTPUT.put_line(PARAGRAF);
        EXCEPTION WHEN NO_DATA_FOUND THEN EXIT;
        END;
    END LOOP;
    UTL_FILE.FCLOSE(TXT_DOSYA1);
END;