--BÝR TEXT DOSYADAN VERÝ OKUYUP BAÞKA BÝR TEXT DOSYAYA VERÝ YAZACAÐIZ--TEXT DOSYAYI KOPYALAMAK

DECLARE
TXT_DOSYA1 UTL_FILE.FILE_TYPE;
TXT_DOSYA2 UTL_FILE.FILE_TYPE;
PARAGRAF VARCHAR2(2000);
BEGIN
    TXT_DOSYA1 := UTL_FILE.FOPEN('TEXT_DIR','DOSYA.TXT','R');
    TXT_DOSYA2:=UTL_FILE.FOPEN('TEXT_DIR','DOSYA2.TXT','W');
    LOOP
    BEGIN
    
        UTL_FILE.GET_LINE(TXT_DOSYA1,PARAGRAF);
        UTL_FILE.PUT_LINE(TXT_DOSYA2,PARAGRAF);
        EXCEPTION WHEN NO_DATA_FOUND THEN EXIT;
        END;
    END LOOP;
   
    UTL_FILE.FCLOSE(TXT_DOSYA1);
    UTL_FILE.FCLOSE(TXT_DOSYA2);
    
END;
