--VERI TABANINDAKÝ BÝR TABLODAN VERI OKUYUP TEXTE YAZDIRMA

DECLARE
CURSOR EMP_OKU IS SELECT EMPNO, ENAME, SAL, JOB FROM EMP ORDER BY EMPNO;
REC_EMP EMP_OKU%ROWTYPE;
PARAGRAF VARCHAR2(2000); -- CURSORDAN GELEN DEÐERLERÝ BURDA TOPLUCAZ
TXTDOSYA UTL_FILE.FILE_TYPE;
BEGIN
    TXTDOSYA:=UTL_FILE.FOPEN('TEXT_DIR','TXTDEMP.TXT','W');
    OPEN EMP_OKU;
    LOOP
        FETCH EMP_OKU INTO REC_EMP;
        EXIT WHEN EMP_OKU%NOTFOUND;
        PARAGRAF:= REC_EMP.EMPNO||' '||REC_EMP.ENAME||' '||REC_EMP.SAL||' '||REC_EMP.JOB;
        UTL_FILE.PUT_LINE(TXTDOSYA,PARAGRAF);
    END LOOP;
    CLOSE EMP_OKU;
    IF UTL_FILE.IS_OPEN(TXTDOSYA) THEN
        UTL_FILE.FCLOSE(TXTDOSYA);
    END IF;
END;
