--XML TABLOLAR ÝLE ÇALIÞMAK
    --SORGU SONUCUNU XML FORMATINA CEVIRMEK(TABLO KOLONLARINI XML TAG OLARAK KULLANMAK)
        --ÖRNEK UYGULAMA: BBÝR TABLODAKÝ BÝLGÝLERÝ XML FORMATINA ÇEVÝRELÝM
            --EMP TABLOSUNDAKÝ BÝLGÝLERÝ XML FORMATINA ÇEVÝRECEK, XMLTYPE TÜRÜNDE  BÝR TABLOYA INSERT EDECEÐÝZ
                    --A) XMLTYPE TABLO OLUÞTURMAK
                    --N)STANDARD BÝR TABLODAKÝ BÝLGÝLERÝ XML FORMATINA ÇEVÝRÝP XMLTYPE FORMATINDAKÝ BÝR TABLOYA INSERT ETMEK
                    
SELECT SYS_XMLAGG(
                XMLELEMENT("EMP",                                                               --TAG OLUÞTURDUK
                            XMLFOREST(E.EMPNO, E.ENAME, E.JOB, E.HIREDATE, E.SAL, E.COMM) -- HANGÝ BÝLGÝLERÝ ALACAÐIMIZI SÖYLÜYORUZ
                            )
)"XML"

FROM EMP E;